version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "7584:3100"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
