const express = require("express");
const fs = require("fs");
const path = require("path");
const compression = require("compression");
const expressStaticGzip = require("express-static-gzip");
const WebSocket = require("ws");
const http = require("http");

const app = express();
const port = process.env.PORT || 3100;
const publicDir = path.join(__dirname, "public");

// Request logging (registered first so static asset requests are logged too)
app.use((req, res, next) => {
    console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);
    next();
});

app.use(compression());
// Serves pre-built .br/.gz variants (scripts/precompress.js) when present,
// falling back to the plain file (which compression() then handles).
app.use(
    expressStaticGzip(publicDir, {
        enableBrotli: true,
        orderPreference: ["br", "gz"],
        serveStatic: {
            maxAge: "1d",
            setHeaders: (res, filePath) => {
                // filePath may be the precompressed variant (.br/.gz) of the file.
                const plainPath = filePath.replace(/\.(br|gz)$/, "");
                if (plainPath.endsWith(".html")) {
                    // The entry point must always revalidate so app updates roll out.
                    res.setHeader("Cache-Control", "no-cache");
                } else if (plainPath.startsWith(path.join(publicDir, "assets"))) {
                    // Versioned assets (requested with ?v=...) can be cached aggressively.
                    res.setHeader("Cache-Control", "public, max-age=604800, immutable");
                }
                // Point DevTools at the split module sources when the source map
                // exists (generated by npm run build, gitignored).
                if (plainPath.endsWith(".js") && fs.existsSync(plainPath + ".map")) {
                    res.setHeader("SourceMap", path.basename(plainPath) + ".map");
                }
            },
        },
    })
);
// The deminified module sources, referenced by the bundles' source maps so
// DevTools can display module files instead of the 8MB+ built bundles.
app.use("/src", express.static(path.join(__dirname, "src"), { maxAge: "1h" }));
app.use(express.json());

const server = http.createServer(app);

const wss = new WebSocket.Server({
    server,
    path: "/license",
});

// Terminate connections whose clients stopped answering protocol-level pings.
const heartbeat = setInterval(() => {
    wss.clients.forEach((ws) => {
        if (ws.isAlive === false) return ws.terminate();
        ws.isAlive = false;
        ws.ping();
    });
}, 30000);
wss.on("close", () => clearInterval(heartbeat));

wss.on("connection", (ws, req) => {
    const url = new URL(req.url, `http://${req.headers.host}`);
    const lang = url.searchParams.get("lang");

    ws.isAlive = true;
    ws.on("pong", () => {
        ws.isAlive = true;
    });

    console.log(`🟢 WebSocket connected with lang=${lang} from ${req.headers.origin}`);

    ws.on("message", (message) => {
        try {
            const parsed = JSON.parse(message.toString());
            if (parsed.name === "ping") {
                ws.send(JSON.stringify({ name: "pong" }));
            } else {
                console.log("📩 Unhandled message:", parsed);
            }
        } catch (e) {
            console.warn("❌ Invalid JSON received:", message.toString());
        }
    });

    ws.on("close", () => {
        console.log("🔌 WebSocket closed");
    });
});

// ---------------------------------------------------------------------------
// Unsplash proxy (optional). The original app never talked to Unsplash
// directly — it went through Corel's server-side proxy, which is gone. If
// UNSPLASH_ACCESS_KEY is set (free key from https://unsplash.com/developers),
// these endpoints re-implement that proxy against the official Unsplash API
// and the library panel's Photos category comes back to life. Without a key
// the integration stays hidden in the UI (see /config.js below).
const UNSPLASH_ACCESS_KEY = process.env.UNSPLASH_ACCESS_KEY || "";
// Overridable for testing against a mock API.
const UNSPLASH_API_BASE = process.env.UNSPLASH_API_BASE || "https://api.unsplash.com";
const UNSPLASH_PAGE_SIZE = 30;

// Small response cache to stay well inside Unsplash's 50 requests/hour demo
// rate limit (repeat category browsing and paging hit the same URLs).
const unsplashCache = new Map();
const UNSPLASH_CACHE_TTL = 10 * 60 * 1000;

async function unsplashFetch(pathAndQuery) {
    const cached = unsplashCache.get(pathAndQuery);
    if (cached && Date.now() - cached.time < UNSPLASH_CACHE_TTL) return cached.data;
    const response = await fetch(UNSPLASH_API_BASE + pathAndQuery, {
        headers: { Authorization: `Client-ID ${UNSPLASH_ACCESS_KEY}`, "Accept-Version": "v1" },
    });
    if (!response.ok) {
        const err = new Error(`Unsplash API responded ${response.status}`);
        // Auth/rate-limit problems are our misconfiguration, not the client's.
        err.status = response.status === 401 || response.status === 403 ? 502 : response.status;
        throw err;
    }
    const data = await response.json();
    if (unsplashCache.size >= 500) unsplashCache.clear();
    unsplashCache.set(pathAndQuery, { time: Date.now(), data });
    return data;
}

// Shape a photo the way the app's library panel expects (see
// src/bundles/designer.browser/1663.js: id, path prefix "element.image.",
// image.thumb/width/height for the masonry layout, user.name/profile for
// the attribution link).
function toLibraryAsset(photo) {
    return {
        id: photo.id,
        path: "element.image.unsplash",
        width: photo.width,
        height: photo.height,
        image: { thumb: photo.urls.small, width: photo.width, height: photo.height },
        user: { name: photo.user.name, profile: photo.user.links.html },
    };
}

app.get("/unsplash/featured", async (req, res, next) => {
    if (!UNSPLASH_ACCESS_KEY) return res.json([]);
    try {
        const page = parseInt(req.query.page, 10) || 1;
        const photos = await unsplashFetch(`/photos?page=${page}&per_page=${UNSPLASH_PAGE_SIZE}&order_by=popular`);
        res.json(photos.map(toLibraryAsset));
    } catch (e) {
        next(e);
    }
});

app.get("/unsplash/search/photos", async (req, res, next) => {
    if (!UNSPLASH_ACCESS_KEY) return res.json([]);
    try {
        const page = parseInt(req.query.page, 10) || 1;
        const query = String(req.query.query || "").trim();
        if (!query) return res.json([]);
        const result = await unsplashFetch(`/search/photos?query=${encodeURIComponent(query)}&page=${page}&per_page=${UNSPLASH_PAGE_SIZE}`);
        res.json((result.results || []).map(toLibraryAsset));
    } catch (e) {
        next(e);
    }
});

// Returns the image URL for a photo as a JSON string — the app fetches the
// response's JSON value directly (gApi.getUnsplashPhotoUrl in module 1663).
app.get("/unsplash/download/photo", async (req, res, next) => {
    if (!UNSPLASH_ACCESS_KEY) return res.status(404).json({ error: "Unsplash integration is not configured" });
    try {
        const id = String(req.query.id || "");
        if (!/^[A-Za-z0-9_-]+$/.test(id)) return res.status(400).json({ error: "invalid photo id" });
        const photo = await unsplashFetch(`/photos/${id}`);
        // Unsplash API guidelines require reporting downloads; fire-and-forget.
        if (photo.links && photo.links.download_location) {
            fetch(photo.links.download_location, {
                headers: { Authorization: `Client-ID ${UNSPLASH_ACCESS_KEY}`, "Accept-Version": "v1" },
            }).catch(() => {});
        }
        const size = String(req.query.size || "regular");
        res.json(photo.urls[size] || photo.urls.regular);
    } catch (e) {
        next(e);
    }
});

// The elements-market API (shapes/stickers/icons...) was never archived. An
// empty listing keeps the library panel's combined search working — it
// concatenates market results with Unsplash results and a failed market call
// would discard both.
app.get("/market", (req, res) => {
    res.json([]);
});

// Runtime config, loaded by index.html before the app bundles. The bundle's
// library UI checks window.UNSPLASH_ENABLED (modules 1662/1664) so features
// with no backend stay hidden instead of showing empty categories.
app.get("/config.js", (req, res) => {
    res.type("application/javascript");
    res.setHeader("Cache-Control", "no-cache");
    res.send(`window.UNSPLASH_ENABLED = ${Boolean(UNSPLASH_ACCESS_KEY)};\n`);
});

app.get("/connection/test", (req, res) => {
    res.send("OK");
});

app.get("/maintenance/status", (req, res) => {
    res.json({ cloud: false, clientAllowed: true });
});

// status 0 = subscriptions disabled, which suppresses the purchase flows
app.get("/subscription/test", (req, res) => {
    res.json({ status: 0 });
});

// Cloud file listing ("Open Recent" and folder browsing): always empty,
// there is no cloud storage anymore.
app.get("/file", (req, res) => {
    res.json([]);
});

app.get("/user/settings", (req, res) => {
    return res.json({
        notifications_disabled: false,
        trialDays: 15,
        quotas: { free: null, pro: null },
        subscription: {
            annual: { productId: null, coupon: "Trial20" },
            extraParameters: { "x-at": null, "x-clickref": null },
        },
        license: { offlineExpirationTime: 1296000000, offlineCountdown: 604800000 },
        reminders: {
            offlineWarning: 86400000,
            proOfferInFree: 1296000000,
            proOfferInTrial: 432000000,
            proOfferInTrialExpired: 1296000000,
            proOfferInTrialExpireSoon: 86400000,
            proOfferInTrialLastWarning: 0,
            proOfferSpecialPrice: 0,
            proExpireSoon: 2592000000,
        },
        flags: {
            welcomeMessage: false,
            windowsStoreAnnouncement: false,
            proOfferSpecialPrice: false,
            proOfferInTrialExpireSoon: true,
            proOfferInTrialLastWarning: true,
        },
    });
});

const SUPPORTED_LOCALES = [
    "de-de",
    "en",
    "zh-cn",
    "pt-br",
    "es-es",
    "fr-fr",
    "pl-pl",
    "ru-ru",
    "tr-tr",
    "cs-cz",
    "zh-tw",
    "it-it",
    "ja-jp",
    "nl-nl",
    "sv-se",
];

app.put("/user", (req, res) => {
    const { locale } = req.body ?? {};

    const normalized = locale?.toLowerCase();
    const languageCode = SUPPORTED_LOCALES.includes(normalized) ? normalized : "en";

    return res.json({
        id: "12345678",
        name: "PlasmaTrap User",
        locale: languageCode,
        email: "example@example.net",
        version: "3.15.0",
        runtime: "Browser",
        settings: {
            notifications_disabled: false,
        },
    });
});

app.get("/user", (req, res) => {
    const { lang } = req.query;

    // Indices match the app's GLocaleLanguage enum (chunk.vendor module 0701):
    // English=0, German=1, Chinese=2, ...
    const languages = {
        0: "en",
        1: "de-DE",
        2: "zh-CN",
        3: "pt-BR",
        4: "es-ES",
        5: "fr-FR",
        6: "pl-PL",
        7: "ru-RU",
        8: "tr-TR",
        9: "cs-CZ",
        10: "zh-TW",
        11: "it-IT",
        12: "ja-JP",
        13: "nl-NL",
        14: "sv-SE",
    };

    const languageCode = languages[lang] || "en";

    return res.json({
        id: "12345678",
        email: "example@example.net",
        email_verified: true,
        email_expire: null,
        login: null,
        name: "Placeholder User",
        // Self-hosted so the app makes no external requests (app icon as
        // placeholder). The ?v= marker makes the app treat it as a real
        // picture avatar (GUser.hasOwnPictureAvatar, module 0177) and render
        // the image instead of falling back to initials.
        avatar: "/assets/prerendered/icon128.png?v=1",
        admin: null,
        flash: null,
        last_seen: "2025-06-14T09:28:26.899Z",
        app: "designer",
        last_update: "2025-06-13T15:08:43.989Z",
        stats: {},
        address: "",
        city: "",
        zip: "",
        state: "",
        country: "",
        trial_created: "2021-09-22T19:58:35.018Z",
        trial_expire: "2026-10-07T19:58:35.018Z",
        pro_created: null,
        pro_expire: null,
        created: "2021-09-22T19:58:32.748Z",
        last_name: "PlasmaTrap",
        settings: {
            flags: {
                welcomeMessage: false,
                proOfferSpecialPrice: true,
                windowsStoreAnnouncement: false,
                proOfferInTrialExpireSoon: true,
                proOfferInTrialLastWarning: true,
            },
            quotas: {
                pro: null,
                free: null,
            },
            license: {},
            reminders: {},
            trialDays: 15,
            subscription: {
                annual: {
                    coupon: "Trial20",
                    productId: null,
                },
                extraParameters: {
                    "x-at": null,
                    "x-clickref": null,
                },
            },
            notifications_disabled: false,
        },
        runtime: "Browser",
        locale: languageCode,
        user_type: "normal",
        deactivated: false,
        legacy: false,
        guest_created: null,
        guest_expire: null,
        version: "3.15.0",
    });
});

// Error handler: return JSON instead of the default HTML error page.
app.use((err, req, res, next) => {
    if (res.headersSent) {
        return next(err);
    }
    const status = err.status || err.statusCode || 500;
    if (status >= 500) {
        console.error(err);
    }
    res.status(status).json({ error: err.message || "Internal Server Error" });
});

server.listen(port, () => {
    console.log(`Server running at http://localhost:${port}`);
});

const shutdown = () => {
    console.log("Shutting down...");
    wss.clients.forEach((ws) => ws.close(1001, "Server shutting down"));
    server.close(() => process.exit(0));
    setTimeout(() => process.exit(0), 3000).unref();
};

process.on("SIGTERM", shutdown);
process.on("SIGINT", shutdown);
