// Map a built-bundle stack-trace position to its split module file.
// Usage: npm run where -- designer.browser.js:49475
//        npm run where -- chunk.vendor 12345
// Reads src/bundles/<name>/linemap.json (regenerated by npm run build).
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");

const args = process.argv.slice(2);
let name, lineNo;
if (args.length === 1 && args[0].includes(":")) {
    const [n, l] = args[0].split(":");
    ((name = n), (lineNo = parseInt(l, 10)));
} else {
    ((name = args[0]), (lineNo = parseInt(args[1], 10)));
}
if (!name || !Number.isInteger(lineNo)) {
    console.error("usage: npm run where -- <bundle>:<line>   e.g. designer.browser.js:49475");
    process.exit(2);
}
name = path.basename(name, ".js");

const dir = path.join(ROOT, "src", "bundles", name);
const linemapPath = path.join(dir, "linemap.json");
if (!fs.existsSync(linemapPath)) {
    console.error(`${linemapPath} not found — run \`npm run build\` first to generate it.`);
    process.exit(2);
}
const { modules } = JSON.parse(fs.readFileSync(linemapPath, "utf8"));
const moduleNames = fs.existsSync(path.join(dir, "names.json")) ? JSON.parse(fs.readFileSync(path.join(dir, "names.json"), "utf8")) : {};

const hits = modules.filter((m) => m.startLine <= lineNo && lineNo <= m.endLine);
if (!hits.length) {
    console.log(`${name}.js:${lineNo} is webpack runtime/glue, not inside a module`);
    process.exit(0);
}
for (const m of hits) {
    // module files carry a one-line "module.exports = " wrapper on line 1,
    // so bundle lines map 1:1 onto file lines within the module's range
    const localLine = lineNo - m.startLine + 1;
    const file = `src/bundles/${name}/${m.id}.js`;
    const label = moduleNames[String(parseInt(m.id, 10))] || moduleNames[m.id];
    console.log(`${name}.js:${lineNo} -> ${file}:${localLine}${label ? `  (${label})` : ""}`);
    const text = fs.readFileSync(path.join(ROOT, file), "utf8").split("\n")[localLine - 1];
    if (text !== undefined) console.log(`    ${text.trim().slice(0, 160)}`);
    if (hits.length > 1) console.log("    (boundary line shared with another module)");
}
